version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1
  node: circleci/node@1.1

executors:
  chrome80-ff72:
    docker:
      - image: 'cypress/browsers:node13.6.0-chrome80-ff72'

workflows:
   build:
     jobs:
       - cypress/run

 #run tests using Chrome browser
 workflows:
   build:
     jobs:
       - cypress/run:
           executor: cypress/browsers-chrome69
           browser: chrome

 # build the app and start server
 workflows:
   build:
     jobs:
       - cypress/run:
           build: "npm run build"
           start: "npm run server"

 run only specific spec file
 workflows:
   build:
     jobs:
       - cypress/run:
           record: true
           spec: "cypress/integration/spec-a.js"
